[project]
name = "chess-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "python-chess>=1.999",
    "torch>=2.7.1",
]
